from . import donation
from . import donation_tax_receipt
from . import donation_campaign
from . import account_payment_mode
from . import account_journal
from . import donation_thanks_template
from . import account_bank_statement
from . import res_partner
from . import res_users
from . import res_company
